### PR TITLE
Apply an additional condition if -XX:-CRIUSecProvider is specified

### PR DESCRIPTION
**Pull request by WilburZjh**
Back-ported from https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/689

### CODE REVIEW

**Comment by WilburZjh** [comment]
@jasonkatonica FYI

**Comment by WilburZjh** [comment]
Build pass: https://hyc-runtimes-jenkins.swg-devops.com/job/Build_JDK11_x86-64_linux_Personal/5972/

**Comment by WilburZjh** [comment]
> I see you changed the title of this PR: The commit message should be similar.

updated

**Comment by keithc-ca** [comment]
Jenkins test sanity xlinux jdk11

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
