### PR TITLE
Fix ludcl refresh logic

### PR DESCRIPTION
**Pull request by theresa-m**
Fixes: https://github.com/eclipse/openj9/issues/8454

Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>

### CODE REVIEW

**Comment by theresa-m** [comment]
fyi @vijaysun-omr

I've run Daytrader 7 startup perf tests with this change resulting the following:

Nightly OpenJ9 build mean startup time: 4880.85 ms
Build with this pr mean startup time: 4854.33 ms

% difference: 
(4854.33-4880.85)/4854.33 = 
**-0.55%**

**Comment by theresa-m** [comment]
@pshipton if you have a chance can you review this to get it moving into the nightlys for our user?

**Comment by pshipton** [comment]
jenkins test sanity,extended,sanity.system,extended.system plinux jdk11

**Comment by pshipton** [comment]
jenkins test sanity,extended,sanity.system,extended.system plinux jdk11

**Pull request merged**
