### PR TITLE
Enable cmake by default on aarch64

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@knn-k are you ready for this change? Is there anything you'd like to validate before it is merged?

I've only tested sanity.functional with cmake (normal and XL), but it passed.

**Comment by knn-k** [comment]
I have no particular concern about enabling CMake.
Yes, I have seen the build results in https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All-11/247/ and https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All-11/250/ .

**Comment by knn-k** [comment]
Cross-building for AArch64 fails with CMake.
```
-- The ASM compiler identification is GNU
-- Found assembler: /root/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- OMR: trace root is '/root/openj9/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/runtime'
-- Starting with CMake version 3.5.1
-- Found Git: /usr/bin/git (found version "2.7.4")
-- Configuring incomplete, errors occurred!
See also "/root/openj9/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/CMakeFiles/CMakeOutput.log".
/root/openj9/openj9-openjdk-jdk11/closed/OpenJ9.gmk:388: recipe for target '/root/openj9/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/cmake.stamp' failed
make[3]: *** [/root/openj9/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/cmake.stamp] Error 1
/root/openj9/openj9-openjdk-jdk11/closed/custom/Main.gmk:56: recipe for target 'j9vm-build' failed
```

I need to add `--with-cmake=no` for cross building.

**Comment by pshipton** [comment]
@knn-k you can revert this if you want, or wait for a fix.

**Comment by knn-k** [comment]
AArch64 builds at adoptopenjdk have been failing after cmake build was enabled, because `cmake` is missing on the build machine.
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/428/consoleText

```
[2020-07-23T23:43:37.792Z] checking for m4... /usr/bin/m4
[2020-07-23T23:43:37.792Z] checking for cmake... no
[2020-07-23T23:43:37.792Z] configure: error: Could not find required tool for CMAKE
[2020-07-23T23:43:37.792Z] configure exiting with result code 1
(... lines omitted ...)
[2020-07-23T23:43:37.792Z] /home/ubuntu/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/make/Init.gmk:124: *** Cannot continue.  Stop.
```

**Comment by pshipton** [comment]
I believe Adopt has already fixed the problem.

**Comment by knn-k** [comment]
It seems not.  The build today failed again with "Could not find required tool for CMAKE".
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/435/

**Comment by dnakamura** [comment]
I'm not familiar with the adopt infrastructure, but from a quick look it appears to be doing a native rather than a cross compile

**Comment by pshipton** [comment]
@sxa you mentioned you knew about the aarch64 cmake problem, do you need an issue opened to fix it?

**Comment by pshipton** [comment]
Created https://github.com/AdoptOpenJDK/openjdk-build/issues/1999

**Comment by pshipton** [comment]
Tracked here https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1462

**Pull request merged**
