### PR TITLE
Keep RSA native resource alive

### PR DESCRIPTION
**Pull request by jerrylui803**
issue https://github.com/ibmruntimes/openj9-openjdk-jdk11/issues/104

Signed-off-by: Jerry Lui <jerrylui@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Looks good, although I expect the other algorithms using openssl need a similar change.

I changed the description so merging this doesn't close #104, because similar change are required for jdk8, even if the RSA code isn't delivered to jdk8 yet.

**Comment by ashbm5** [comment]
@pshipton in all other OpenSSL backed crypto operations: Digest, AES-CBC and AES-GCM there isn't this kind of behaviour where a native routine takes in a ptr to a native resource that may be deallocated due to object finalization in Java. This is something unique so far for RSA due to the interaction between RSACore and RSA Key classes. In the other crypto operations there is only a single crypto class that takes in primitive types and a native pointer that is allocated and de-allocated by that same crypto class.

@jerrylui803 please confirm.

**Comment by jerrylui803** [comment]
> @pshipton in all other OpenSSL backed crypto operations: Digest, AES-CBC and AES-GCM there isn't this kind of behaviour where a native routine takes in a ptr to a native resource that may be deallocated due to object finalization in Java. This is something unique so far for RSA due to the interaction between RSACore and RSA Key classes. In the other crypto operations there is only a single crypto class that takes in primitive types and a native pointer that is allocated and de-allocated by that same crypto class.
> 
> @jerrylui803 please confirm.

confirmed

**Comment by pshipton** [comment]
Confirmed the following is sufficient to keep the key alive, so this change is not required.

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/eaa2f0279376379fc0b47bb9a8fdeb0f236a80b6/src/java.base/share/classes/sun/security/rsa/RSACore.java#L128

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/eaa2f0279376379fc0b47bb9a8fdeb0f236a80b6/src/java.base/share/classes/sun/security/rsa/RSACore.java#L157

**Pull request closed without merging**
