### PR TITLE
Update ignore list based on M2 build

### PR DESCRIPTION
**Pull request by JinhangZhang**

### CODE REVIEW

**Comment by JinhangZhang** [comment]
@JasonFengJ9 @jasonkatonica @llxia @KostasTsiounis FYI

**Comment by JasonFengJ9** [comment]
jenkins copyright check

**Comment by JasonFengJ9** [comment]
jenkins line endings check

**Review by JasonFengJ9 — APPROVED** [review]

**Comment by JasonFengJ9** [comment]
@JinhangZhang pls port this to 0.46 release branch.

**Pull request merged**
