### PR TITLE
Make openjdk tag search local to branch

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Issue https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/101

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins test sanity xlinux

**Comment by andrew-m-leonard** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/2242/

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by keithc-ca** [comment]
Tag search is no longer required since #168 - closing.

**Pull request closed without merging**
