### PR TITLE
Don't test unavailable algorithms

### PR DESCRIPTION
**Pull request by keithc-ca**
Support for EdDSA, Ed25519 and Ed448 was added in Java 15.

Fixes: https://github.com/eclipse-openj9/openj9/issues/17579.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Strange: the test job didn't use this change; instead it used the [current openj9 branch - b33416dc888](https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/b33416dc888ee757c6761810bf416f37c6b17e8a).

```
 Using OPENJDK_REPO = [11:[aarch64_linux:https://github.com/ibmruntimes/openj9-openjdk-jdk11.git]] OPENJDK_BRANCH = [11:[aarch64_linux:openj9]] OPENJDK_SHA = [11:[aarch64_linux:]]
```

I've launched a grinder instead: https://openj9-jenkins.osuosl.org/job/Grinder/2502.

**Comment by keithc-ca** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/669 should fix that failure.

**Comment by keithc-ca** [comment]
> I think this is a known issue as well, the test change is not picked up, it was determined a low priority item.

This may become a more important issue with an increased focus on testing security-related changes.

**Review by JasonFengJ9 — APPROVED** [review]
LGTM - the grinder passed the tests in question.

**Pull request merged**
