### PR TITLE
Updates to ensure correct copyright order

### PR DESCRIPTION
**Pull request by groeges**
Signed-off-by: Steve Groeger <GROEGES@uk.ibm.com>

### CODE REVIEW

**Comment by groeges** [comment]
PR for issue: https://github.ibm.com/runtimes/openjdk-contribution/issues/641

**Comment by groeges** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Pull request merged**
