### PR TITLE
Reverts #3, javac compile with source 11 target 11

### PR DESCRIPTION
**Pull request by pshipton**
Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity zlinux

**Comment by DanHeidinga** [comment]
jenkins test sanity zlinux

**Comment by pshipton** [comment]
jenkins test sanity zlinux

**Comment by DanHeidinga** [comment]
Relaunched the build as https://github.com/eclipse/openj9/pull/2898 may have already fixed this

**Comment by DanHeidinga** [comment]
The only failures in the Sanity build are known issues:
```
GeneralTest suite / JCL_TEST_Java-Lang
org.openj9.test.java.lang.Test_String.test_toLowerCase_lithuanian
org.openj9.test.java.lang.Test_String.test_toLowerCase_lithuanian
```

**Comment by DanHeidinga** [comment]
The failing copyright check makes sense as this is reverting a change and restoring the file to an unmodified state.

**Pull request merged**
