### PR TITLE
Alter error message to match the openj9 error message

### PR DESCRIPTION
**Pull request by M-Davies**
Signed-off-by: M-Davies [morgandavies2020@gmail.com](mailto:morgandavies2020@gmail.com)

See: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1288

### CODE REVIEW

**Comment by M-Davies** [comment]
Jenkins copyright check

**Comment by M-Davies** [comment]
Jenkins Signed-off-by Check

**Comment by M-Davies** [comment]
Jenkins check

**Comment by M-Davies** [comment]
Jenkins signed off by check

**Comment by M-Davies** [comment]
jenkins signed off by check

**Comment by M-Davies** [comment]
jenkins signed off by check

**Comment by DanHeidinga** [comment]
Tests that bind tightly like this to a particular error message are prone to breaking when error messages are modified.  They also give users the idea that exception messages are stable enough to parse (which shouldn't be done either as it makes the code brittle)

I'd suggest proposing a patch to OpenJDK to remove the error message check to make the code more maintainable.  If OpenJDK accepts that change, we could back port it here.

**Comment by M-Davies** [comment]
jenkins signed off by check

**Comment by M-Davies** [comment]
> I'd suggest proposing a patch to OpenJDK to remove the error message check to make the code more maintainable. If OpenJDK accepts that change, we could back port it here.

Where would be the appropriate place to suggest these changes?

**Comment by DanHeidinga** [comment]
@andrew-m-leonard Can you help to identify the correct openjdk mailing list?

**Comment by andrew-m-leonard** [comment]
this is a core-libs-dev issue since it's a java.base test:
https://mail.openjdk.java.net/pipermail/core-libs-dev/
@M-Davies can you raise a openjdk-contribution issue for this and we can contribute...

**Pull request closed without merging**
