### PR TITLE
Revert Update Harfbuzz to 7.0.1

### PR DESCRIPTION
**Pull request by pshipton**
Issue https://github.com/eclipse-openj9/openj9/issues/17759

### CODE REVIEW

**Comment by keithc-ca** [comment]
I think this is missing 3319f3173433e376e3d799b0dbb7ba8e0d70398d (#632).

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/3319f3173433e376e3d799b0dbb7ba8e0d70398d is already in the v0.40.0-release branch.

**Comment by pshipton** [comment]
Keith said, you can see the changes are missing when comparing against the 0.38 release branch. I cherry picked the change and added it.

**Comment by keithc-ca** [comment]
> [3319f31](https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/3319f3173433e376e3d799b0dbb7ba8e0d70398d) is already in the v0.40.0-release branch.

You're right: The v0.40.0-release branch is currently at 20e0e5315796df31dbe6c69e5681b0a4d240ed2c and `merge-base` agrees:
```sh
$ git merge-base --is-ancestor 3319f3173433e376e3d799b0dbb7ba8e0d70398d 20e0e5315796df31dbe6c69e5681b0a4d240ed2c && echo yes
yes
```
I think that change was lost via a merge that accepted 1a361540adae01024eb97ad99e3184873bb9a925 verbatim.

**Comment by keithc-ca** [comment]
Jenkins compile aix jdk11 depends eclipse-openj9/openj9#v0.40.0-release eclipse-openj9/openj9-omr#v0.40.0-release

**Comment by pshipton** [comment]
jdk_imageio testing at https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2584/
There is one failure but seems unrelated.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
