### PR TITLE
Backport parts of 8300169: Build failure with clang-15

### PR DESCRIPTION
**Pull request by pshipton**
https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/f441ba047

### CODE REVIEW

**Comment by keithc-ca** [comment]
Why is the addition of `deprecated-non-prototype` to `DISABLED_WARNINGS_clang` not needed for `BUILD_LIBSPLASHSCREEN` in `Awt2dLibraries.gmk`?

**Comment by pshipton** [comment]
I did builds of both amac, xmac with xcode/clang 15 and it wasn't a problem so I didn't backport it.
https://github.ibm.com/runtimes/infrastructure/issues/8853#issuecomment-95904505

**Comment by keithc-ca** [comment]
Jenkins compile amac,osx,win jdk11

**Comment by keithc-ca** [comment]
```
[2024-11-05T01:38:18.115Z] error: unknown warning option '-Wno-deprecated-non-prototype' [-Werror,-Wunknown-warning-option]
[2024-11-05T01:38:18.115Z] make[3]: *** [/Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/support/native/java.desktop/libawt/AlphaMath.o] Error 1
[2024-11-05T01:38:18.874Z] make[2]: *** [java.desktop-libs] Error 2
[2024-11-05T01:38:18.874Z] make[2]: *** Waiting for unfinished jobs....
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/view/Pull%20Requests/job/PullRequest-OpenJDK11/211/

**Comment by pshipton** [comment]
Jenkins compile amac jdk11

**Comment by pshipton** [comment]
Once it's working, we should try compilation on aix since it uses clang.

**Comment by pshipton** [comment]
Jenkins compile xmac,aix jdk11

**Comment by pshipton** [comment]
aix had a git clone problem.

Jenkins compile aix jdk11

**Comment by pshipton** [comment]
Looks like the AIX build will be successful. I didn't re-run Windows, but I assume the change to DISABLED_WARNINGS_clang won't affect it. The earlier build https://openj9-jenkins.osuosl.org/view/Pull%20Requests/job/PullRequest-OpenJDK11/211/ passed on Windows.

**Comment by keithc-ca** [comment]
> Once it's working, we should try compilation on aix since it uses clang.

No, AIX uses xlc:
```
[2024-11-05T13:00:14.269Z] configure: Using default toolchain xlc (IBM XL C/C++)
```

**Review by keithc-ca — APPROVED** [review]

**Comment by pshipton** [comment]
We're running xlclang, but makes sense it would be treated differently.

**Pull request merged**
