### PR TITLE
WIP: TEST: DO NOT MERGE (OR REVIEW) - Test commit for testing copyrightChecker

### PR DESCRIPTION
**Pull request by groeges**
This PR is a test PR to test the new copyrightCheck Jenkins script

Signed-off-by: Steve Groeger <GROEGES@uk.ibm.com>

### CODE REVIEW

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Comment by groeges** [comment]
steve copyright check

**Pull request closed without merging**
