### PR TITLE
Fix typo in reference to NativeECKeyPairGenerator

### PR DESCRIPTION
**Pull request by keithc-ca**
See https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/783/files#r1588208020.

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
jenkins compile amac jdk11

**Comment by JasonFengJ9** [comment]
```
16:40:24  [consumer_0] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_aarch64_mac_Personal/488/OpenJ9-JDK11-aarch64_mac-20240503-062821.tar.gz
16:40:24  [consumer_1] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_aarch64_mac_Personal/488/test-images.tar.gz
16:40:28  [consumer_2] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_aarch64_mac_Personal/488/debug-image.tar.gz
```
The build succeeded.

**Review by JasonFengJ9 — APPROVED** [review]

**Comment by pshipton** [comment]
This problem was introduced by https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/650
@jasonkatonica @KostasTsiounis should we be adding this fix to the 0.44 release?

**Comment by KostasTsiounis** [comment]
> This problem was introduced by #650 @jasonkatonica @KostasTsiounis should we be adding this fix to the 0.44 release?

The PR will be ready today, so we can definitely add it in there if we can.

**Comment by pshipton** [comment]
OpenJDK22:		https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/57
OpenJDK21:		https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/154
OpenJDK17:		https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/348
OpenJDK11:		https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/777

**Pull request merged**
