### PR TITLE
Fix comment issues and add code to support AIX unbundled

### PR DESCRIPTION
**Pull request by groeges**
Signed-off-by: Steve Groeger <GROEGES@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins test sanity xlinux

**Comment by andrew-m-leonard** [comment]
jenkins test sanity aix

**Comment by pshipton** [comment]
@andrew-m-leonard note the aix sanity run done here will not include the CryptoTest, as this test is excluded for AIX, so a pass won't indicate these changes are working on AIX. 

I did run a custom build and test on Steve's openj9-openssl branch, which passed the CryptoTest. I see the sha tested is the same as this PR.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/55/ - sha 317d9e9
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/316/

**Comment by pshipton** [comment]
jenkins test sanity osx

**Comment by pshipton** [comment]
AIX CryptoTest being enabled in https://github.com/eclipse/openj9/pull/4922

**Comment by pshipton** [comment]
AIX CryptoTest in eclipse/openj9#4922 succeeded

**Pull request merged**
