### PR TITLE
Enable cmake by default on windows

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
I want to run all the testing, but I'll stage it so it doesn't consume all the resources at one time.

jenkins compile sanity,extended wincm jdk11

**Comment by pshipton** [comment]
jenkins test sanity,extended wincm jdk11

**Comment by pshipton** [comment]
jenkins test sanity.system,extended.system,sanity.openjdk wincm jdk11

**Comment by pshipton** [comment]
I haven't seen this failure before afaik.

PatchModuleImgTest_UnexportedType_0 failed, trying it again in a grinder https://ci.eclipse.org/openj9/job/Grinder/1177/
```
STF 18:22:28.642 - +------ Step 9 - (Negative test) Include a new package that is not exported and check if the public type cannot be accessed
STF 18:22:28.642 - | Run foreground process
STF 18:22:28.642 - |   Program:     F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal/openjdk-tests/TKG/test_output_16055686054615/PatchModuleImgTest_UnexportedType_0/20201116-182213-PatchModuleImageTest/tmp/6.XpJVM/bin/java
STF 18:22:28.642 - |   Mnemonic:    OT3
STF 18:22:28.642 - |   Echo:        ECHO_ON
STF 18:22:28.642 - |   Expectation: NON_ZERO_EXIT [1] within 5m
STF 18:22:28.642 - |
STF 18:22:28.643 - Running command: F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal/openjdk-tests/TKG/test_output_16055686054615/PatchModuleImgTest_UnexportedType_0/20201116-182213-PatchModuleImageTest/tmp/6.XpJVM/bin/java --add-reads com.test=ALL-UNNAMED --patch-module com.hello=F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal/openjdk-tests/TKG/test_output_16055686054615/PatchModuleImgTest_UnexportedType_0/20201116-182213-PatchModuleImageTest/modules/7.com.hello.jar -classpath F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal/jvmtest/system/systemtest_prereqs/junit-4.12/junit-4.12.jar;F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal/jvmtest/system/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar org.junit.runner.JUnitCore net.adoptopenjdk.test.modularity.junit.TestOverrideUsingAppModuleAndNewPackage
STF 18:22:28.643 - Redirecting stderr to F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal/openjdk-tests/TKG/test_output_16055686054615/PatchModuleImgTest_UnexportedType_0/20201116-182213-PatchModuleImageTest/results/9.OT3.stderr
STF 18:22:28.643 - Redirecting stdout to F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal/openjdk-tests/TKG/test_output_16055686054615/PatchModuleImgTest_UnexportedType_0/20201116-182213-PatchModuleImageTest/results/9.OT3.stdout
STF 18:22:28.652 - Monitoring processes: OT3
OT3 stderr jvm.dll preloadLibrary: LoadLibrary(F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal\openjdk-tests\TKG\test_output_16055686054615\PatchModuleImgTest_UnexportedType_0\20201116-182213-PatchModuleImageTest\tmp\6.XpJVM\bin\compressedrefs\j9vm29.dll) error: ce
OT3 stderr jvm.dll preloadLibrary: LoadLibrary(F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal\openjdk-tests\TKG\test_output_16055686054615\PatchModuleImgTest_UnexportedType_0\20201116-182213-PatchModuleImageTest\tmp\6.XpJVM\bin\compressedrefs\j9hookable29.dll) error: ce
OT3 stderr jvm.dll failed to load: j9vm29
STF 18:22:28.720 - **FAILED** Process OT3 ended with exit code (3221225477) and not the expected exit code/s (1)
STF 18:22:28.720 - Monitoring Report Summary:
STF 18:22:28.720 -   o Process OT3 ended with exit code (3221225477) and not the expected exit code/s (1)
STF 18:22:28.721 - Killing processes: OT3
STF 18:22:28.721 -   o Process OT3 is not running
**FAILED** at step 9 ((Negative test) Include a new package that is not exported and check if the public type cannot be accessed). Expected return value=0 Actual=1 at F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_cm_Personal/openjdk-tests/\TKG\test_output_16055686054615\PatchModuleImgTest_UnexportedType_0/20201116-182213-PatchModuleImageTest/execute.pl line 395.
STF 18:22:28.768 - **FAILED** execute script failed. Expected return value=0 Actual=1
```
3221225477 is 0xC0000005 which is Access Violation, although I don't see anything describing a crash in the stdout/stderr in the artifacts. tmp\6.XpJVM is there, so I tried running `java -version` on it, which works fine.

**Comment by pshipton** [comment]
Grinder passed, try a few more https://ci.eclipse.org/openj9/job/Grinder/1178/

**Comment by dnakamura** [comment]
oh I have seen that error before in my testing. I'll try to pull up the relevant issue, but it boiled down to a problem with the test code since the path name got too long on certain files. The original issue was resolved by shortening the names of certain files. However because the new `_cm` spec name is 3 characters longer I think it pushed things back over the limit

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
lgtm

**Pull request merged**
