### PR TITLE
Make jdi connector listenMap thread safe

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder_Advanced/19/

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
openjdk community currently state JDI is no specified as thread-safe...

**Comment by DanHeidinga** [comment]
> openjdk community currently state JDI is no specified as thread-safe...

@andrew-m-leonard Is there a link to that discussion?  Does the OJDK community object to improving the thread safety of JDI?

**Comment by andrew-m-leonard** [comment]
https://mail.openjdk.java.net/pipermail/serviceability-dev/2019-June/028316.html
@DanHeidinga well 50:50, Alan makes the point it is not supposed to be thread-safe currently, and that great lengths need to be taken to "study" how to retro-fit it if required. I've deferred it to a JDI SME, as I don't understand the full implications, and I felt I was effectively getting Alan to point out all the issues, and he doesn't have the time to study it... hence we need a JDI SME to get involved.

**Comment by andrew-m-leonard** [comment]
This PR is closed as the change had morphed a lot from this!

**Pull request closed without merging**
