### PR TITLE
Merge latest openj9 changes to 0.41

### PR DESCRIPTION
**Pull request by pshipton**
Manual merge, fixing the merge conflict in get_j9_source.sh

### CODE REVIEW

**Review by JasonFengJ9 — APPROVED** [review]

**Comment by keithc-ca** [comment]
This doesn't appear to have achieved what I think you expected for `get_j9_source.sh`; see https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/v0.41.0-release/closed/get_j9_source.sh#L59-L63.

**Comment by pshipton** [comment]
I did that intentionally, to avoid any accidental breakage from a new largely untested change. 0.41 has already diverged from the head stream so there is no benefit. We'll use the change for 0.42 to avoid having to create PRs like this one. I may end up always hard coding the branch names before we ship to avoid side effects.

**Comment by keithc-ca** [comment]
> I may end up always hard coding the branch names

Wasn't the whole point of that series of pull requests to avoid the need for those manual changes?

**Comment by pshipton** [comment]
No, it's not the manual change I wanted to avoid, but having to create PRs like this to pick up the latest changes.

**Comment by keithc-ca** [comment]
> If we continue to make the manual change

My preference is that we don't do that.

**Comment by pshipton** [comment]
Sure, we can see how it goes, and if anyone complains about the magic.

**Pull request merged**
