### PR TITLE
Include vcruntime140_1.dll when compiling with VS2019

### PR DESCRIPTION
**Pull request by pshipton**
[Internal issue](https://github.ibm.com/runtimes/javanext/issues/356) - `JVMJ9VM011W Unable to load j9jit29: JVMPORT015E Unable to resolve shared library references - a prerequisite shared library may be missing`

The OpenJDK code is backported from jdk17.
8242468: VS2019 build missing vcruntime140_1.dll

In the PR build, vcruntime140_1.dll is included in the bin directory and the java.base.jmod (as expected).
On a system without vcruntime140_1.dll, the PR build runs without error, while the last nightly build gets the error shown above.

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile win jdk11

**Comment by pshipton** [comment]
jenkins compile win jdk11

**Comment by pshipton** [comment]
jenkins compile win jdk11

**Comment by babsingh** [comment]
- Why didn't we change the copyright to 2022?
- Otherwise, LGTM.

**Comment by pshipton** [comment]
The OpenJDK changes backported were made in 2020, so I used that date.

**Comment by pshipton** [comment]
@keithc-ca do you have an opinion on what copyright date to use?

**Comment by keithc-ca** [comment]
I think we should also backport the copyright dates from jdk17.

**Review by babsingh — APPROVED** [review]

**Comment by keithc-ca** [comment]
@babsingh Why did you merge this before @pshipton had a chance to update the copyright dates?

**Comment by babsingh** [comment]
- As per https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/574#issuecomment-1242545375, the copyrights already matched the backport. 
- As per https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/574#issuecomment-1243917089, you wanted the copyrights from the backport to be used.
- So, no more changes were needed.

**Comment by babsingh** [comment]
@keithc-ca Was your message misinterpreted? I can make the correction.

**Comment by keithc-ca** [comment]
Perhaps I didn't look at the dates closely enough. For example, `spec.gmk.in` has a current copyright date in jdk17 of 2021, but this change leaves that date at 2020: that sort of discrepancy was the basis for my comment. However, if we consider the date when the change was committed to jdk17, it is actually 2020, so I think everything is fine. Sorry for the noise.

**Pull request merged**
