### PR TITLE
Replace Oracle libjsig.so with OpenJ9 version

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkinx compile xlinux

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by keithc-ca** [comment]
I expect we'll want to make the same changes here as I've requested in #52.

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
@keithc-ca @groeges If you could review again please

**Comment by andrew-m-leonard** [comment]
ready again...

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
jenkins test sanity xlinux

**Pull request merged**
