### PR TITLE
Add debug-image target

### PR DESCRIPTION
**Pull request by keithc-ca**
* copy debuginfo files for openj9 artifacts
* collect files (*.debuginfo, *.pdb, etc.) into images/debug-image

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test sanity aix,osx,xlinux,win jdk11

**Comment by keithc-ca** [comment]
Marking as 'WIP' until I correct the paths for `.dSYM` folders on OSX.

**Comment by keithc-ca** [comment]
The proper paths are now computed for all platforms.

**Comment by pshipton** [comment]
Jenkins test sanity aix,osx,plinux,win jdk11

**Pull request merged**
