### PR TITLE
Set OPENJDK_TAG from merged openjdk level

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/2293/

**Comment by andrew-m-leonard** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/2301/

**Comment by andrew-m-leonard** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/2309/

**Comment by keithc-ca** [comment]
Ignoring copyright failure for closed/openjdk-tag.gmk which is intended to be generated by the process of merging content from openjdk.

**Pull request merged**
