### PR TITLE
Backport 8308801, 8308022 to jdk11 

### PR DESCRIPTION
**Pull request by pshipton**
8308801: update for deprecated sprintf for libnet in java.base
https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/152d486

8308022: update for deprecated sprintf for java.base
https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/6af76ec98f9

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test sanity alinux,win jdk11

**Comment by pshipton** [comment]
Jenkins test sanity.functional alinux jdk11

**Comment by pshipton** [comment]
I don't think the failures in https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Personal/310/ are related. The problematic change was reverted and I've re-run the testing.

**Comment by pshipton** [comment]
Again there is a failure on alinux, cmdLineTest_gpTest_0 timeout, but I don't think it's related.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
